version: '3.9'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nishit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bfs_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
        - 5432:5432
  
  adminer:
      image: adminer
      restart: always
      ports:
        - 7000:7000

volumes:
  postgres_data:
